### ISSUE TITLE
[feature-question] Is this possible to add onto 3rd party responses like Open AI?

### ISSUE THREAD

**Issue by KevinDanikowski** [jwkirchenbauer/lm-watermarking#11]
Is there a typical method of implementing this onto the outputs from a 3rd party like Open AI after the text has been generated? Is it even possible / practical?

**Comment by jwkirchenbauer** [comment]
In short, as a general comment, it's currently not possible to watermark the outputs of an API model that doesn't provide the probability distribution over the full vocabulary (or a large part of it) at each token generation step. OpenAI only provides the top 5 token probabilities and this isn't really enough to add the watermark in the way we proposed, at least not in an efficient manner. 

Regarding your particular proposal about applying a watermark "after the text has been generated", this amounts to a _paraphrasing_ task where the text is rewritten in a biased way by substituting tokens or spans of tokens such that there is an increase in the overall fraction of tokens lying in their respective green partitions.

As a remark, it should be noted that the tediousness of this task, and the fact that it reduces to rewriting the vast majority of the text, is exactly why _removing_ the watermark is difficult. In expectation, any pair of neighboring tokens in a general piece of text on the internet/from an un-watermarked model, contains one green and one red (under a $\gamma=0.5$ scheme), and thus one of those tokens needs to be swapped in order to increase the overall green fraction. 

That said, we describe an iterative rewriting procedure in Section 7.1 of our paper using a T5 language model as an attacker trying to scrub the watermark by replacing tokens and hopefully decreasing the green ratio. This procedure could be adapted to instead directly select replacement spans that _increase_ the green fraction of tokens in a text. To do this, one needs access to the logic of the watermark random number generator, prime seed, and scheme definition, like it is defined in the `WatermarkBase` class in this repository.
