### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by LeoStrange26** [jwkirchenbauer/lm-watermarking#15]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 23.69 GiB total capacity; 22.80 GiB already allocated; 188.94 MiB free; 22.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

hope you can propose a method that allows it to run on a single card (RTX 3090) with 24GB VRAM, or provide the minimum required configuration for running it.

**Comment by jwkirchenbauer** [comment]
The watermark processor and detector itself have negligible cost in terms of extra memory. The issue you're having is most likely due to trying to run a larger model than can fit on your GPU. I suggest either choosing a smaller model, and/or running the model in half precision or with further quantization.
