### ISSUE TITLE
problems with running code in ./experients

### ISSUE THREAD

**Issue by LeoStrange26** [jwkirchenbauer/lm-watermarking#17]
after running ./experients/run_watermarking.py 2 times with parameters:
(1)  --limit_indices 30 bl_proportion 0.5 --bl_logit_bias 2.0 --oracle_model_name facebook/opt-1.3b(other parameters using examples shown in readme.md)
(2) --limit_indices 30 bl_proportion 0.5 --bl_logit_bias 2.0 --oracle_model_name facebook/opt-1.3b(other parameters using examples shown in readme.md)
then running ./experients/process_rows.py (having modified the relevant paths)
bugs occur:(like this)
baseline input replacement bug occurred!
no_bl_output input replacement bug occurred!
w_bl_output input replacement bug occurred!

hoping you can solve this

**Comment by LeoStrange26** [comment]
another question is that in ./experients blacklist=greenlist or redlist?

**Comment by jwkirchenbauer** [comment]
Hi there, so that warning being printed is just a warning about something that I noticed in that early version of the data generation code. It doesn't make the data invalid, it's just some rows are a bit malformed by some faulty string replacement logic. And yes, as you can see, this code is from the earliest version of experiments where we used the "blacklist" terminology. Blacklist corresponds to redlist, but for this reason and others I have different suggestion for you.

My general suggestion is to run the newer code in the `watermark_reliability_release` subdirectory. It is a much more mature set of steps with better documentation. The `experiments` dir in the top of the repo was mostly left there to preserve the code used to generate data in the first paper, but not really recommended for further use. Instead the generate, attack, evaluate pipeline scripts from the newer work going to probably be easier for you to use. Minimally, the green/red convention is fully adopted in this code, which will lessen confusion.

After the review process for the new work is complete we will likely restructure the repository in order to direct people to the more updated version of the code.

**Comment by jwkirchenbauer** [comment]
Also, since you seem to be in the process of trying to walk through the code, lets stick to this issue for further questions rather than making a new one for each request, just to keep things organized.

**Comment by LeoStrange26** [comment]
What equipment was used in the experiment? It seems that using RTX3090 is a bit challenging.

**Comment by LeoStrange26** [comment]
While running the (Empirical error rates for watermark detection using multinomial sampling and beam search. Each row is averaged over ∼ 500 generated sequences of length T = 200 ± 5) using the code in watermark_reliability_release.,we have type-I error rate at most 4%, totally different from 0 which is descibed in the paper.

**Comment by jwkirchenbauer** [comment]
Could you describe a bit more what model, dataset, and watermark settings you're using? Also what z-score threshold are you using to compute the FPR?

The output entropy matters a lot in terms of how much watermark is embedded and this, its possible that the experimental combination you're using is slightly different in this respect.

**Comment by jwkirchenbauer** [comment]
Feel free to make a new issue in the future if questions arise, thanks!
