### ISSUE TITLE
relatively high perplexity on baseline complete text & other datasets

### ISSUE THREAD

**Issue by quwenjie** [jwkirchenbauer/lm-watermarking#19]
I am currently using the official code for "On the Reliability of Watermarks for Large Language
Models", testing on C4 dataset. I found that the baseline completion PPL measured using facebook/opt-6.7b oracle model is >9 and I think this is relatively high. However when I use llama models to generate watermark text and non-watermark text, the perplexity seems to be only around 2 or 3(under default parameters). I am not sure whether I made some mistake to get such a large PPL on human written text baseline. I am wondering if you could help to try to measure this.

Also, could you provide the hyperparamaters used for generation and evaluation on LFQA dataset and Wikitext dataset? Thanks a lot!

**Comment by jwkirchenbauer** [comment]
So, first a comment on your perplexity observations... 

I'm not referencing any specific statistic we reported in this statement, but generally, weaker language models assign lower perplexities to model generated texts and higher (and more variable) perplexities to real human written text. This is in some sense the performance gap between LLMs and the real human distribution. 

So, llama generations will be "less surprising", i.e. lower perplexity, to a weaker oracle such as OPT than real text since those machine generated samples are made of the token choices that a similar type of model made. This principle is  actually the precise phenomenon that score based detectors like the older RoBERTa based GPT2 detector (https://openai-openai-detector.hf.space/) and to some extent, DetectGPT, rely on to perform detection!

---

Now, addressing your clarifying questions on experimental setup:

In terms of generation parameters, we used multinomial sampling with `temperature=0.7` for all generation runs regardless of model. This might not be optimal from a model performance perspective, but since the watermark strength heavily depends on entropy, we wanted to fix this parameter. It also also allowed us to observe that vicuna, architecturally identical to llama, but further tuned, behaves differently with the same watermark setting (Appendix A.3).

Unless mentioned otherwise in each set of experiments, the watermarking parameters were `gamma=0.25` and `delta=2.0`.

In particular, one important experiment where we deviated from this was the human study. The examples that were generated based on LFQA prompts for the purposes of human paraphrasing and human rating were generated using a watermark with settings `gamma=0.25` and `delta=4.0` as is mentioned in the section Appendix A.9.2. They were sampled with a maximum length of 600 tokens, but then further down-selected as described in the paper.

Generally the prompt creation strategies had the following settings:
If the target length `max_new_tokens` was `200` then the `min_prompt_tokens` was `50`.
If the target length `max_new_tokens` was `600` then the `min_prompt_tokens` was `100`.
If the target length `max_new_tokens` was `1000` then the `min_prompt_tokens` was `200`.
When attempting to get `N` samples following args were set for the `generation_pipeline.py` script:
```
min_generations = N
input_truncation_strategy = "completion_length"
input_filtering_strategy = "prompt_and_completion_length"
output_filtering_strategy = "max_new_tokens"
```

How does this work? This is described in `PIPELINE.md` in this repo, but somewhat succintly:
The program would loop over the available data (say in wikitext103) and for each row, check whether the input was such that when `max_new_tokens` was removed from the end of the current sample (the "truncation strategy"), there were still at least `min_prompt_tokens` left of text in the sample (the "input filtering strategy"). Then the prompt would be fed to the language model and the "row" would only be recorded as a valid `1` out of the `N` requested, if the output from the model was at least `max_new_tokens` long (the "output filtering strategy").

For LFQA only, the setting was: 
```
input_truncation_strategy = "no_truncation"
input_filtering_strategy = "no_filter"
output_filtering_strategy = "no_filter"
```
This is because for this dataset we were not _creating_ prompts, because the dataset rows were already formatted as short questions, and so these argument values turned off all the oversampling and filtering logic in the pipeline and produce a generation for every row in that dataset.

If this does not answer all your questions please follow up - thanks for your interest in the work!

(PS... of course while writing this, I have realized that some of these things should be added to the arxiv copy of the work. thanks for helping point that out!)

**Comment by quwenjie** [comment]
Thanks a lot for your clarification! It helps a lot!
