### ISSUE TITLE
unable to run the demo

### ISSUE THREAD

**Issue by cechae** [jwkirchenbauer/lm-watermarking#30]
Hello! 
I wanted to run the demo on Hugging face but I got this error: Runtime error.

Also, when I tried running "python demo_watermark.py --model_name_or_path facebook/opt-6.7b", it is getting stuck after the "Generating with...".

**Comment by jwkirchenbauer** [comment]
I restarted the huggingface space demo! It sometimes errors at random times due to huggingface serving infrastructure changes/restarts. Should be useable now.

In term of a local demo, can you show me what output you get on the command line when you run the demo script?

We'd actually probably recommend that you start here: [lm-watermarking#how-to-use-the-watermark-in-your-own-code](https://github.com/jwkirchenbauer/lm-watermarking#how-to-use-the-watermark-in-your-own-code)

The demo script is actually what runs the interaactive huggingface space gradio application, and that's not the simplest way to test out the watermark on a huggingface model. The few lines of code at the link above are the core of whats needed to make some watermarked generations and run the detector over them.

Let me know if you have more questions!

**Comment by cechae** [comment]
Thanks a lot! I am able to see the Huggingface space demo!

Here is the output I get on the command line when I run "python demo_watermark.py --model_name_or_path facebook/opt-6.7b".


<img width="1083" alt="output_terminal" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/48112292/e2ef7ce2-b210-44f0-a97a-30267554eb76">

**Comment by jwkirchenbauer** [comment]
Sorry for the delayed response. If you're still having problems, make a new issue with the specific error you're encountering, thanks!
