### ISSUE TITLE
about the model 

### ISSUE THREAD

**Issue by LeoStrange26** [jwkirchenbauer/lm-watermarking#33]
It's hard to reach the baseline presenting in the paper.
And opt-1.3b (default setting) isn't good enough —— the original output without the watermark is not good already(with many repetition sentences). 
Maybe authors can give us the experiment settings? thx

**Comment by jwkirchenbauer** [comment]
The small OPT models used in the original work (experiments run late in 2022) are quite poor text generators even without the watermark. Repetition is a standard degeneracy that they exhibit and the "simple" version of our watermark does exacerbate this issue, especially at strong values of delta.

I suggest you try a newer/better base model if you're interested in understanding the realistic impact on output quality as new open source models generate much better text in base form, and we find the the watermark, especially in the self-hash setting doesn't impact text quality in any significant way, especially under realistic generative benchmark evaluations rather than a pure perplexity or KL(orig_model,wm_model) check which directly isolates the divergence of the wm distribution from the main distribution.

Llama2, Mistral, or other strong 7b-13b finetunes are good starting points in 2024!
