### ISSUE TITLE
runtime error in huggingface demo，Could you fix it? Thanks.

### ISSUE THREAD

**Issue by benny108** [jwkirchenbauer/lm-watermarking#37]
![p1](https://github.com/jwkirchenbauer/lm-watermarking/assets/131588333/eb7acc4e-6061-4006-8f31-d06aa2223e89)

**Comment by jwkirchenbauer** [comment]
Hey there, this is actually a weird error and I'm not sure why it suddenly started occurring. It doesn't really have anything to do with our code it seems.
Looking into the underlying issue...

**Comment by jwkirchenbauer** [comment]
Currently, I resolved it by limiting the demo to just llama2.

We originally supported calling some other API models served by huggingface inference servers, but I believe that we no longer have access to those, so that might have been the reason why it started failing.

Feel free to reach out if there is another issue/issues persist.
