### ISSUE TITLE
Error when input text is longer than model's max_sequence

### ISSUE THREAD

**Issue by bangawayoo** [jwkirchenbauer/lm-watermarking#8]
Hi John. 
Thank you for the great work!

I noticed a bug in the legacy code in the `./experiments/` directory due to using the `model_max_seq_len=None` argument when tokenizing the input text. An error occurs on the C4 dataset for the sample index=74 as the tokenizer defaults to no truncation. (EDIT: using the example hyperparameter configuration in `./experiments/README.md`)

This can be easily fixed by commenting out the above argument and uncommenting the `model_max_seq_len=model.config.max_position_embeddings`.

I just wanted to check if using the max_position_embeddings to truncate the input text is okay? Wondering why this was commented out 🤔. 

Thanks.

**Comment by jwkirchenbauer** [comment]
I think this is less of a bug and more of a usage quirk? Basically you should set the truncation strategy argument for prompts such that this doesn't happen.

You can see from looking at the `launch.py` file, that there are a variety of arguments controlling the logic used to turn samples from a language modeling/web dataset like C4 into "prompts" , but I think the most important here is `input_truncation_strategy`. This is what determines how the prompt is constructed either by setting the desired prompt length (value `"prompt_length"`) or by setting the amount to be sliced off the end of the raw text (value `"completion_length"`). Added together with the value of the `max_new_tokens` argument this determines the maximum length of tokens that the model will have to manage. This needs to be less than the model's maximum allowed, but you're right there isn't a logical check for that, sorry! 

If you don't configure these correctly for your model, then errors can occur once the model has generated more tokens and the sum of the max new tokens + prompt length is greater than the model's max length. The reason the `model_max_seq_len` is set very large as default in that internal function in `watermark.py` is because in the setup I wanted exact control over prompt and completion lengths in different experiments and so I wasn't relying on "autotruncation" at that internal part of the code which would have happened silently.

This old code is really only designed to run the very specific prompt creation strategy from the paper, but is not required at all to validate how the watermark performs on general language modeling data. Let me know if you're still having trouble!

**Comment by bangawayoo** [comment]
Thanks for the reply! That clears my confusion. 
I will have a look at `launch.py`.
