### ISSUE TITLE
Configurations for replicating the results in the paper

### ISSUE THREAD

**Issue by bangawayoo** [jwkirchenbauer/lm-watermarking#9]
Hi!

I am trying to replicate some of the results in the paper to analyze the outputs, but I am getting different oracle PPL.
Do you have plans to release the configuration files(e.g. gen_table_meta.json, shell scripts) for the results in the paper? 

For instance, I am trying to replicate one of the results in Figure 2 right (greedy) when using \sigma=2, \gamma=0.5, but I get PPL around 2.0, which is higher than expected.
This is my configuration. Would you help me out?
```
python run_watermarking.py \
    --model_name facebook/opt-1.3b \
    --dataset_name c4 \
    --dataset_config_name realnewslike \
    --max_new_tokens 200 \
    --min_prompt_tokens 50 \
    --limit_indices 500 \
    --input_truncation_strategy completion_length \
    --input_filtering_strategy prompt_and_completion_length \
    --output_filtering_strategy no_filter \
    --dynamic_seed markov_1 \
    --bl_proportion 0.5 \
    --bl_logit_bias 2.0 \
    --bl_type soft \
    --store_spike_ents True \
    --num_beams 1 \
    --use_sampling False \
    --sampling_temp 0.7 \
    --oracle_model_name facebook/opt-2.7b \
    --run_name example_run \
    --output_dir ./all_runs/${OUTPUT_DIR} \
    --load_prev_generations F --no_wandb T --all_gas_no_eos T  \
    --no_repeat_ngram_size 8 # tried 0 as well

```

I also uncommented this part following "In the runs using greedy and beam search decoding [...]  we truncate all sequences to T = 200." in Section 6. 
```
    output_length_filtered_dataset = generations_dataset.filter(output_check,
                                                                batched=False,
                                                                with_indices=False)
```

Thanks.

**Comment by jwkirchenbauer** [comment]
For that specific set of runs, figure 2 right, you should modify your parameters above so that:
```
--min_sample_tokens 0 \
--min_prompt_tokens 200 \
--max_new_tokens 500 \
--all_gas_no_eos True \
--no_repeat_ngram_size 0 \
--input_truncation_strategy prompt_length \
--input_filtering_strategy prompt_and_completion_length \
--output_filtering_strategy no_filter \
```

For the part you uncommented, leave the code commented/or delete it that you mention above, because this was a refactor. Now the length checking is covered by code at [line 349](https://github.com/jwkirchenbauer/lm-watermarking/blob/main/experiments/run_watermarking.py#L349).

Then, you will get 500 rows (this is because `all_gas_no_eos ` ensures that no sequence ends before length) of length 500. Then at the analysis step, I slice all those generations to ~200 tokens while computing their green fraction, z-score etc. (`process_rows.py` has a flag inside it `limit_output_tokens=200` that does this for you) This introduces a bit of a mismatch between the length PPL was computed at (all 500 tokens) versus the length z is computed (the leading 200 tokens). But this is actually a bit "harder" on the method because allowing longer sequences would simply produce higher Z scores (so we cap them all at the same length as in figure 2 left), but the PPL of the whole sequence is not likely to be lower than the PPL of the first 200 tokens, so if anything the original untruncated sequences would have registered as higher z for a given PPL.

Ideally we would not like to have such complicated lengths settings here, but the point/problem is that greedy decoding, and especially beam search, produces shorter length generations naturally. This is even worse for weaker, small models like these OPT variants we could run ourselves, so we had to do some tweaking to get long enough outputs to measure.

You running `no_repeat_ngram_size=8` and getting higher PPL like 2.0 is exactly as expected, we saw this too. This is because PPL actually is flawed in that it doesn't penalize repetition (the opposite actually) so when you turn on the penalty, your PPL seems worse. However, **_absolute PPL is not so important, what matters is the difference between watermarked and unwatermarked generations using the same settings._**

---
So, for what it's worth, the sampling decoding setting is the primary set of experiments for the paper because this is the setting we use to derive our theoretical results. We wanted to show that the watermark works in the greedy decoding setting, but we expect in practice these outputs may not be as high quality, and may incur repetition, as these are known properties of greedy decoding and beam search. Today, sampling based decoding for LLMs like GPT is standard (and more performant in many generation quality evaluations).

**Comment by bangawayoo** [comment]
Thank you for the detailed answer!
I could reproduce the PPL number with the above configuration. 

By the way, the smaller version of OPT seems to generate a lot of repetitive sentences even when `no_repeat_ngram_size=8` is used. So I will stick with sampling for my analysis. 

I do have some follow-ups:
- For sampling decoding strategy, was `max_new_tokens` also set to 500 and then truncated?  
- For output filtering, what were some of the reasons you chose to save the filtered-out examples in `processed_examples` instead of completely filtering them out as done before the refactor? I am asking because it seems like PPL will be computed for the filtered-out examples in the current implementations. 


Thanks.

**Comment by jwkirchenbauer** [comment]
Yes, the tendency to repeat is a widely reproduced weakness of these small models, especially in the greedy decoding setting. We're currently working on some testing on much larger models at the 20B and 100B+ level to avoid these issues.

Followups:

- No, the over-generation and then sub selection approach was used for the sampling experiments because under multinomial sampling, these models will frequently generate 200 tokens without the need for EOS suppression. I recorded an oversampling ratio of about 2-4x, meaning we needed to sample 1000-2000 prompts in order to get 500 "natural" generations of length ~200.

- We saved all the examples simply for performing extra analysis under a relaxation of the length constraint (computing statistics where the samples contain variable token lengths, say from 20-200). Further, we didn't want to waste compute, so since the GPU being used was up and running, and we'd already produced those shorter than desired outputs, we might as well get the PPL. Also, computing teacher forced PPL for all examples was actually a cheap enough operation as the entire output (prompt+generation) in our experiments still fit within the context length of the model. Each calculation only requires one model forward call and this could be batched to make it way faster actually! I was just originally careful during implementation to make sure the PPL was only computed on the generated tokens and not the prompt, via masking, since that could skew results. Never converted that function to batching.
